//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sma_log2sql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smardEntities : DbContext
    {
        public smardEntities()
            : base("name=smardEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adrmap_energymeter> adrmap_energymeter { get; set; }
        public DbSet<log_energymeter> log_energymeter { get; set; }
        public DbSet<smadevice> smadevice { get; set; }
        public DbSet<smadevicetype> smadevicetype { get; set; }
    }
}
