//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 2/05/2015 23:04:26
namespace smardMeter.SMArdWcfDataServiceReference
{
    
    /// <summary>
    /// There are no comments for smardEntities in the schema.
    /// </summary>
    public partial class smardEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new smardEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public smardEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "smardModel", "smardMeter.SMArdWcfDataServiceReference");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("smardMeter.SMArdWcfDataServiceReference", global::System.StringComparison.Ordinal))
            {
                return string.Concat("smardModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for adrmap_energymeter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<adrmap_energymeter> adrmap_energymeter
        {
            get
            {
                if ((this._adrmap_energymeter == null))
                {
                    this._adrmap_energymeter = base.CreateQuery<adrmap_energymeter>("adrmap_energymeter");
                }
                return this._adrmap_energymeter;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<adrmap_energymeter> _adrmap_energymeter;
        /// <summary>
        /// There are no comments for log_energymeter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<log_energymeter> log_energymeter
        {
            get
            {
                if ((this._log_energymeter == null))
                {
                    this._log_energymeter = base.CreateQuery<log_energymeter>("log_energymeter");
                }
                return this._log_energymeter;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<log_energymeter> _log_energymeter;
        /// <summary>
        /// There are no comments for smadevice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<smadevice> smadevice
        {
            get
            {
                if ((this._smadevice == null))
                {
                    this._smadevice = base.CreateQuery<smadevice>("smadevice");
                }
                return this._smadevice;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<smadevice> _smadevice;
        /// <summary>
        /// There are no comments for smadevicetype in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<smadevicetype> smadevicetype
        {
            get
            {
                if ((this._smadevicetype == null))
                {
                    this._smadevicetype = base.CreateQuery<smadevicetype>("smadevicetype");
                }
                return this._smadevicetype;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<smadevicetype> _smadevicetype;
        /// <summary>
        /// There are no comments for adrmap_energymeter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToadrmap_energymeter(adrmap_energymeter adrmap_energymeter)
        {
            base.AddObject("adrmap_energymeter", adrmap_energymeter);
        }
        /// <summary>
        /// There are no comments for log_energymeter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTolog_energymeter(log_energymeter log_energymeter)
        {
            base.AddObject("log_energymeter", log_energymeter);
        }
        /// <summary>
        /// There are no comments for smadevice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTosmadevice(smadevice smadevice)
        {
            base.AddObject("smadevice", smadevice);
        }
        /// <summary>
        /// There are no comments for smadevicetype in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTosmadevicetype(smadevicetype smadevicetype)
        {
            base.AddObject("smadevicetype", smadevicetype);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"smardModel\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm\"><Ent" +
                "ityType Name=\"adrmap_energymeter\"><Key><PropertyRef Name=\"address\" /><PropertyRe" +
                "f Name=\"type\" /></Key><Property Name=\"address\" Type=\"Edm.Int32\" Nullable=\"false\"" +
                " /><Property Name=\"type\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"des" +
                "cription\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" />" +
                "<Property Name=\"log_column\" Type=\"Edm.String\" MaxLength=\"16\" FixedLength=\"false\"" +
                " Unicode=\"false\" /></EntityType><EntityType Name=\"log_energymeter\"><Key><Propert" +
                "yRef Name=\"device\" /><PropertyRef Name=\"logtime\" /></Key><Property Name=\"device\"" +
                " Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"logtime\" Type=\"Edm.Int32\" N" +
                "ullable=\"false\" /><Property Name=\"p_in_l1_act\" Type=\"Edm.Int32\" /><Property Name" +
                "=\"p_in_l2_act\" Type=\"Edm.Int32\" /><Property Name=\"p_in_l3_act\" Type=\"Edm.Int32\" " +
                "/><Property Name=\"p_in_all_act\" Type=\"Edm.Int32\" /><Property Name=\"q_in_l1_act1\"" +
                " Type=\"Edm.Int32\" /><Property Name=\"q_in_l2_act1\" Type=\"Edm.Int32\" /><Property N" +
                "ame=\"q_in_l3_act1\" Type=\"Edm.Int32\" /><Property Name=\"q_in_all_act1\" Type=\"Edm.I" +
                "nt32\" /><Property Name=\"s_in_l1_act1\" Type=\"Edm.Int32\" /><Property Name=\"s_in_l2" +
                "_act1\" Type=\"Edm.Int32\" /><Property Name=\"s_in_l3_act1\" Type=\"Edm.Int32\" /><Prop" +
                "erty Name=\"s_in_all_act1\" Type=\"Edm.Int32\" /><Property Name=\"p_out_l1_act1\" Type" +
                "=\"Edm.Int32\" /><Property Name=\"p_out_l2_act1\" Type=\"Edm.Int32\" /><Property Name=" +
                "\"p_out_l3_act1\" Type=\"Edm.Int32\" /><Property Name=\"p_out_all_act1\" Type=\"Edm.Int" +
                "32\" /><Property Name=\"q_out_l1_act1\" Type=\"Edm.Int32\" /><Property Name=\"q_out_l2" +
                "_act1\" Type=\"Edm.Int32\" /><Property Name=\"q_out_l3_act1\" Type=\"Edm.Int32\" /><Pro" +
                "perty Name=\"q_out_all_act1\" Type=\"Edm.Int32\" /><Property Name=\"s_out_l1_act1\" Ty" +
                "pe=\"Edm.Int32\" /><Property Name=\"s_out_l2_act1\" Type=\"Edm.Int32\" /><Property Nam" +
                "e=\"s_out_l3_act1\" Type=\"Edm.Int32\" /><Property Name=\"s_out_all_act1\" Type=\"Edm.I" +
                "nt32\" /><Property Name=\"cosphi_l1\" Type=\"Edm.Int32\" /><Property Name=\"cosphi_l2\"" +
                " Type=\"Edm.Int32\" /><Property Name=\"cosphi_l3\" Type=\"Edm.Int32\" /><Property Name" +
                "=\"thd_l1\" Type=\"Edm.Int32\" /><Property Name=\"thd_l2\" Type=\"Edm.Int32\" /><Propert" +
                "y Name=\"thd_l3\" Type=\"Edm.Int32\" /><Property Name=\"v_l1\" Type=\"Edm.Int32\" /><Pro" +
                "perty Name=\"v_l2\" Type=\"Edm.Int32\" /><Property Name=\"v_l3\" Type=\"Edm.Int32\" /><P" +
                "roperty Name=\"p_in_l1_sum\" Type=\"Edm.Int64\" /><Property Name=\"p_in_l2_sum\" Type=" +
                "\"Edm.Int64\" /><Property Name=\"p_in_l3_sum\" Type=\"Edm.Int64\" /><Property Name=\"p_" +
                "in_all_sum\" Type=\"Edm.Int64\" /><Property Name=\"q_in_l1_sum\" Type=\"Edm.Int64\" /><" +
                "Property Name=\"q_in_l2_sum\" Type=\"Edm.Int64\" /><Property Name=\"q_in_l3_sum\" Type" +
                "=\"Edm.Int64\" /><Property Name=\"q_in_all_sum\" Type=\"Edm.Int64\" /><Property Name=\"" +
                "s_in_l1_sum\" Type=\"Edm.Int64\" /><Property Name=\"s_in_l2_sum\" Type=\"Edm.Int64\" />" +
                "<Property Name=\"s_in_l3_sum\" Type=\"Edm.Int64\" /><Property Name=\"s_in_all_sum\" Ty" +
                "pe=\"Edm.Int64\" /><Property Name=\"p_out_l1_sum\" Type=\"Edm.Int64\" /><Property Name" +
                "=\"p_out_l2_sum\" Type=\"Edm.Int64\" /><Property Name=\"p_out_l3_sum\" Type=\"Edm.Int64" +
                "\" /><Property Name=\"p_out_all_sum\" Type=\"Edm.Int64\" /><Property Name=\"q_out_l1_s" +
                "um\" Type=\"Edm.Int64\" /><Property Name=\"q_out_l2_sum\" Type=\"Edm.Int64\" /><Propert" +
                "y Name=\"q_out_l3_sum\" Type=\"Edm.Int64\" /><Property Name=\"q_out_all_sum\" Type=\"Ed" +
                "m.Int64\" /><NavigationProperty Name=\"smadevice\" Relationship=\"smardModel.FK_log_" +
                "energymeter_smadevice\" ToRole=\"smadevice\" FromRole=\"log_energymeter\" /></EntityT" +
                "ype><EntityType Name=\"smadevice\"><Key><PropertyRef Name=\"deviceID\" /></Key><Prop" +
                "erty Name=\"deviceID\" Type=\"Edm.Int32\" Nullable=\"false\" p6:StoreGeneratedPattern=" +
                "\"Identity\" xmlns:p6=\"http://schemas.microsoft.com/ado/2009/02/edm/annotation\" />" +
                "<Property Name=\"devicetype\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"" +
                "serialnumber\" Type=\"Edm.Decimal\" Precision=\"18\" Scale=\"0\" /><Property Name=\"host" +
                "name\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Pro" +
                "perty Name=\"ipaddress\" Type=\"Edm.String\" MaxLength=\"50\" FixedLength=\"false\" Unic" +
                "ode=\"true\" /><Property Name=\"targetaddress\" Type=\"Edm.String\" MaxLength=\"50\" Fix" +
                "edLength=\"false\" Unicode=\"true\" /><Property Name=\"firmware\" Type=\"Edm.String\" Ma" +
                "xLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><NavigationProperty Name=\"log_" +
                "energymeter\" Relationship=\"smardModel.FK_log_energymeter_smadevice\" ToRole=\"log_" +
                "energymeter\" FromRole=\"smadevice\" /><NavigationProperty Name=\"smadevicetype\" Rel" +
                "ationship=\"smardModel.FK_smadevice_smadevicetype\" ToRole=\"smadevicetype\" FromRol" +
                "e=\"smadevice\" /></EntityType><EntityType Name=\"smadevicetype\"><Key><PropertyRef " +
                "Name=\"devicetypeID\" /></Key><Property Name=\"devicetypeID\" Type=\"Edm.Int32\" Nulla" +
                "ble=\"false\" /><Property Name=\"devicetypeName\" Type=\"Edm.String\" Nullable=\"false\"" +
                " MaxLength=\"50\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"devicetypeC" +
                "lass\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"10\" FixedLength=\"true\" Unico" +
                "de=\"true\" /><NavigationProperty Name=\"smadevice\" Relationship=\"smardModel.FK_sma" +
                "device_smadevicetype\" ToRole=\"smadevice\" FromRole=\"smadevicetype\" /></EntityType" +
                "><Association Name=\"FK_log_energymeter_smadevice\"><End Type=\"smardModel.smadevic" +
                "e\" Role=\"smadevice\" Multiplicity=\"1\" /><End Type=\"smardModel.log_energymeter\" Ro" +
                "le=\"log_energymeter\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"" +
                "smadevice\"><PropertyRef Name=\"deviceID\" /></Principal><Dependent Role=\"log_energ" +
                "ymeter\"><PropertyRef Name=\"device\" /></Dependent></ReferentialConstraint></Assoc" +
                "iation><Association Name=\"FK_smadevice_smadevicetype\"><End Type=\"smardModel.smad" +
                "evicetype\" Role=\"smadevicetype\" Multiplicity=\"1\" /><End Type=\"smardModel.smadevi" +
                "ce\" Role=\"smadevice\" Multiplicity=\"*\" /><ReferentialConstraint><Principal Role=\"" +
                "smadevicetype\"><PropertyRef Name=\"devicetypeID\" /></Principal><Dependent Role=\"s" +
                "madevice\"><PropertyRef Name=\"devicetype\" /></Dependent></ReferentialConstraint><" +
                "/Association></Schema><Schema Namespace=\"sma_log2sql\" xmlns=\"http://schemas.micr" +
                "osoft.com/ado/2009/11/edm\"><EntityContainer Name=\"smardEntities\" m:IsDefaultEnti" +
                "tyContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"http://schemas.microso" +
                "ft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"adrmap_energymeter\" EntityTy" +
                "pe=\"smardModel.adrmap_energymeter\" /><EntitySet Name=\"log_energymeter\" EntityTyp" +
                "e=\"smardModel.log_energymeter\" /><EntitySet Name=\"smadevice\" EntityType=\"smardMo" +
                "del.smadevice\" /><EntitySet Name=\"smadevicetype\" EntityType=\"smardModel.smadevic" +
                "etype\" /><AssociationSet Name=\"FK_log_energymeter_smadevice\" Association=\"smardM" +
                "odel.FK_log_energymeter_smadevice\"><End Role=\"log_energymeter\" EntitySet=\"log_en" +
                "ergymeter\" /><End Role=\"smadevice\" EntitySet=\"smadevice\" /></AssociationSet><Ass" +
                "ociationSet Name=\"FK_smadevice_smadevicetype\" Association=\"smardModel.FK_smadevi" +
                "ce_smadevicetype\"><End Role=\"smadevice\" EntitySet=\"smadevice\" /><End Role=\"smade" +
                "vicetype\" EntitySet=\"smadevicetype\" /></AssociationSet></EntityContainer></Schem" +
                "a></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for smardModel.adrmap_energymeter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// address
    /// type
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("adrmap_energymeter")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("address", "type")]
    public partial class adrmap_energymeter : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new adrmap_energymeter object.
        /// </summary>
        /// <param name="address">Initial value of address.</param>
        /// <param name="type">Initial value of type.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static adrmap_energymeter Createadrmap_energymeter(int address, int type)
        {
            adrmap_energymeter adrmap_energymeter = new adrmap_energymeter();
            adrmap_energymeter.address = address;
            adrmap_energymeter.type = type;
            return adrmap_energymeter;
        }
        /// <summary>
        /// There are no comments for Property address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int address
        {
            get
            {
                return this._address;
            }
            set
            {
                this.OnaddressChanging(value);
                this._address = value;
                this.OnaddressChanged();
                this.OnPropertyChanged("address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _address;
        partial void OnaddressChanging(int value);
        partial void OnaddressChanged();
        /// <summary>
        /// There are no comments for Property type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int type
        {
            get
            {
                return this._type;
            }
            set
            {
                this.OntypeChanging(value);
                this._type = value;
                this.OntypeChanged();
                this.OnPropertyChanged("type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _type;
        partial void OntypeChanging(int value);
        partial void OntypeChanged();
        /// <summary>
        /// There are no comments for Property description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// There are no comments for Property log_column in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string log_column
        {
            get
            {
                return this._log_column;
            }
            set
            {
                this.Onlog_columnChanging(value);
                this._log_column = value;
                this.Onlog_columnChanged();
                this.OnPropertyChanged("log_column");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _log_column;
        partial void Onlog_columnChanging(string value);
        partial void Onlog_columnChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for smardModel.log_energymeter in the schema.
    /// </summary>
    /// <KeyProperties>
    /// device
    /// logtime
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("log_energymeter")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("device", "logtime")]
    public partial class log_energymeter : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new log_energymeter object.
        /// </summary>
        /// <param name="device">Initial value of device.</param>
        /// <param name="logtime">Initial value of logtime.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static log_energymeter Createlog_energymeter(int device, int logtime)
        {
            log_energymeter log_energymeter = new log_energymeter();
            log_energymeter.device = device;
            log_energymeter.logtime = logtime;
            return log_energymeter;
        }
        /// <summary>
        /// There are no comments for Property device in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int device
        {
            get
            {
                return this._device;
            }
            set
            {
                this.OndeviceChanging(value);
                this._device = value;
                this.OndeviceChanged();
                this.OnPropertyChanged("device");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _device;
        partial void OndeviceChanging(int value);
        partial void OndeviceChanged();
        /// <summary>
        /// There are no comments for Property logtime in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int logtime
        {
            get
            {
                return this._logtime;
            }
            set
            {
                this.OnlogtimeChanging(value);
                this._logtime = value;
                this.OnlogtimeChanged();
                this.OnPropertyChanged("logtime");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _logtime;
        partial void OnlogtimeChanging(int value);
        partial void OnlogtimeChanged();
        /// <summary>
        /// There are no comments for Property p_in_l1_act in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> p_in_l1_act
        {
            get
            {
                return this._p_in_l1_act;
            }
            set
            {
                this.Onp_in_l1_actChanging(value);
                this._p_in_l1_act = value;
                this.Onp_in_l1_actChanged();
                this.OnPropertyChanged("p_in_l1_act");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _p_in_l1_act;
        partial void Onp_in_l1_actChanging(global::System.Nullable<int> value);
        partial void Onp_in_l1_actChanged();
        /// <summary>
        /// There are no comments for Property p_in_l2_act in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> p_in_l2_act
        {
            get
            {
                return this._p_in_l2_act;
            }
            set
            {
                this.Onp_in_l2_actChanging(value);
                this._p_in_l2_act = value;
                this.Onp_in_l2_actChanged();
                this.OnPropertyChanged("p_in_l2_act");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _p_in_l2_act;
        partial void Onp_in_l2_actChanging(global::System.Nullable<int> value);
        partial void Onp_in_l2_actChanged();
        /// <summary>
        /// There are no comments for Property p_in_l3_act in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> p_in_l3_act
        {
            get
            {
                return this._p_in_l3_act;
            }
            set
            {
                this.Onp_in_l3_actChanging(value);
                this._p_in_l3_act = value;
                this.Onp_in_l3_actChanged();
                this.OnPropertyChanged("p_in_l3_act");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _p_in_l3_act;
        partial void Onp_in_l3_actChanging(global::System.Nullable<int> value);
        partial void Onp_in_l3_actChanged();
        /// <summary>
        /// There are no comments for Property p_in_all_act in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> p_in_all_act
        {
            get
            {
                return this._p_in_all_act;
            }
            set
            {
                this.Onp_in_all_actChanging(value);
                this._p_in_all_act = value;
                this.Onp_in_all_actChanged();
                this.OnPropertyChanged("p_in_all_act");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _p_in_all_act;
        partial void Onp_in_all_actChanging(global::System.Nullable<int> value);
        partial void Onp_in_all_actChanged();
        /// <summary>
        /// There are no comments for Property q_in_l1_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> q_in_l1_act1
        {
            get
            {
                return this._q_in_l1_act1;
            }
            set
            {
                this.Onq_in_l1_act1Changing(value);
                this._q_in_l1_act1 = value;
                this.Onq_in_l1_act1Changed();
                this.OnPropertyChanged("q_in_l1_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _q_in_l1_act1;
        partial void Onq_in_l1_act1Changing(global::System.Nullable<int> value);
        partial void Onq_in_l1_act1Changed();
        /// <summary>
        /// There are no comments for Property q_in_l2_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> q_in_l2_act1
        {
            get
            {
                return this._q_in_l2_act1;
            }
            set
            {
                this.Onq_in_l2_act1Changing(value);
                this._q_in_l2_act1 = value;
                this.Onq_in_l2_act1Changed();
                this.OnPropertyChanged("q_in_l2_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _q_in_l2_act1;
        partial void Onq_in_l2_act1Changing(global::System.Nullable<int> value);
        partial void Onq_in_l2_act1Changed();
        /// <summary>
        /// There are no comments for Property q_in_l3_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> q_in_l3_act1
        {
            get
            {
                return this._q_in_l3_act1;
            }
            set
            {
                this.Onq_in_l3_act1Changing(value);
                this._q_in_l3_act1 = value;
                this.Onq_in_l3_act1Changed();
                this.OnPropertyChanged("q_in_l3_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _q_in_l3_act1;
        partial void Onq_in_l3_act1Changing(global::System.Nullable<int> value);
        partial void Onq_in_l3_act1Changed();
        /// <summary>
        /// There are no comments for Property q_in_all_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> q_in_all_act1
        {
            get
            {
                return this._q_in_all_act1;
            }
            set
            {
                this.Onq_in_all_act1Changing(value);
                this._q_in_all_act1 = value;
                this.Onq_in_all_act1Changed();
                this.OnPropertyChanged("q_in_all_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _q_in_all_act1;
        partial void Onq_in_all_act1Changing(global::System.Nullable<int> value);
        partial void Onq_in_all_act1Changed();
        /// <summary>
        /// There are no comments for Property s_in_l1_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> s_in_l1_act1
        {
            get
            {
                return this._s_in_l1_act1;
            }
            set
            {
                this.Ons_in_l1_act1Changing(value);
                this._s_in_l1_act1 = value;
                this.Ons_in_l1_act1Changed();
                this.OnPropertyChanged("s_in_l1_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _s_in_l1_act1;
        partial void Ons_in_l1_act1Changing(global::System.Nullable<int> value);
        partial void Ons_in_l1_act1Changed();
        /// <summary>
        /// There are no comments for Property s_in_l2_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> s_in_l2_act1
        {
            get
            {
                return this._s_in_l2_act1;
            }
            set
            {
                this.Ons_in_l2_act1Changing(value);
                this._s_in_l2_act1 = value;
                this.Ons_in_l2_act1Changed();
                this.OnPropertyChanged("s_in_l2_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _s_in_l2_act1;
        partial void Ons_in_l2_act1Changing(global::System.Nullable<int> value);
        partial void Ons_in_l2_act1Changed();
        /// <summary>
        /// There are no comments for Property s_in_l3_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> s_in_l3_act1
        {
            get
            {
                return this._s_in_l3_act1;
            }
            set
            {
                this.Ons_in_l3_act1Changing(value);
                this._s_in_l3_act1 = value;
                this.Ons_in_l3_act1Changed();
                this.OnPropertyChanged("s_in_l3_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _s_in_l3_act1;
        partial void Ons_in_l3_act1Changing(global::System.Nullable<int> value);
        partial void Ons_in_l3_act1Changed();
        /// <summary>
        /// There are no comments for Property s_in_all_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> s_in_all_act1
        {
            get
            {
                return this._s_in_all_act1;
            }
            set
            {
                this.Ons_in_all_act1Changing(value);
                this._s_in_all_act1 = value;
                this.Ons_in_all_act1Changed();
                this.OnPropertyChanged("s_in_all_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _s_in_all_act1;
        partial void Ons_in_all_act1Changing(global::System.Nullable<int> value);
        partial void Ons_in_all_act1Changed();
        /// <summary>
        /// There are no comments for Property p_out_l1_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> p_out_l1_act1
        {
            get
            {
                return this._p_out_l1_act1;
            }
            set
            {
                this.Onp_out_l1_act1Changing(value);
                this._p_out_l1_act1 = value;
                this.Onp_out_l1_act1Changed();
                this.OnPropertyChanged("p_out_l1_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _p_out_l1_act1;
        partial void Onp_out_l1_act1Changing(global::System.Nullable<int> value);
        partial void Onp_out_l1_act1Changed();
        /// <summary>
        /// There are no comments for Property p_out_l2_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> p_out_l2_act1
        {
            get
            {
                return this._p_out_l2_act1;
            }
            set
            {
                this.Onp_out_l2_act1Changing(value);
                this._p_out_l2_act1 = value;
                this.Onp_out_l2_act1Changed();
                this.OnPropertyChanged("p_out_l2_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _p_out_l2_act1;
        partial void Onp_out_l2_act1Changing(global::System.Nullable<int> value);
        partial void Onp_out_l2_act1Changed();
        /// <summary>
        /// There are no comments for Property p_out_l3_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> p_out_l3_act1
        {
            get
            {
                return this._p_out_l3_act1;
            }
            set
            {
                this.Onp_out_l3_act1Changing(value);
                this._p_out_l3_act1 = value;
                this.Onp_out_l3_act1Changed();
                this.OnPropertyChanged("p_out_l3_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _p_out_l3_act1;
        partial void Onp_out_l3_act1Changing(global::System.Nullable<int> value);
        partial void Onp_out_l3_act1Changed();
        /// <summary>
        /// There are no comments for Property p_out_all_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> p_out_all_act1
        {
            get
            {
                return this._p_out_all_act1;
            }
            set
            {
                this.Onp_out_all_act1Changing(value);
                this._p_out_all_act1 = value;
                this.Onp_out_all_act1Changed();
                this.OnPropertyChanged("p_out_all_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _p_out_all_act1;
        partial void Onp_out_all_act1Changing(global::System.Nullable<int> value);
        partial void Onp_out_all_act1Changed();
        /// <summary>
        /// There are no comments for Property q_out_l1_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> q_out_l1_act1
        {
            get
            {
                return this._q_out_l1_act1;
            }
            set
            {
                this.Onq_out_l1_act1Changing(value);
                this._q_out_l1_act1 = value;
                this.Onq_out_l1_act1Changed();
                this.OnPropertyChanged("q_out_l1_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _q_out_l1_act1;
        partial void Onq_out_l1_act1Changing(global::System.Nullable<int> value);
        partial void Onq_out_l1_act1Changed();
        /// <summary>
        /// There are no comments for Property q_out_l2_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> q_out_l2_act1
        {
            get
            {
                return this._q_out_l2_act1;
            }
            set
            {
                this.Onq_out_l2_act1Changing(value);
                this._q_out_l2_act1 = value;
                this.Onq_out_l2_act1Changed();
                this.OnPropertyChanged("q_out_l2_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _q_out_l2_act1;
        partial void Onq_out_l2_act1Changing(global::System.Nullable<int> value);
        partial void Onq_out_l2_act1Changed();
        /// <summary>
        /// There are no comments for Property q_out_l3_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> q_out_l3_act1
        {
            get
            {
                return this._q_out_l3_act1;
            }
            set
            {
                this.Onq_out_l3_act1Changing(value);
                this._q_out_l3_act1 = value;
                this.Onq_out_l3_act1Changed();
                this.OnPropertyChanged("q_out_l3_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _q_out_l3_act1;
        partial void Onq_out_l3_act1Changing(global::System.Nullable<int> value);
        partial void Onq_out_l3_act1Changed();
        /// <summary>
        /// There are no comments for Property q_out_all_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> q_out_all_act1
        {
            get
            {
                return this._q_out_all_act1;
            }
            set
            {
                this.Onq_out_all_act1Changing(value);
                this._q_out_all_act1 = value;
                this.Onq_out_all_act1Changed();
                this.OnPropertyChanged("q_out_all_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _q_out_all_act1;
        partial void Onq_out_all_act1Changing(global::System.Nullable<int> value);
        partial void Onq_out_all_act1Changed();
        /// <summary>
        /// There are no comments for Property s_out_l1_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> s_out_l1_act1
        {
            get
            {
                return this._s_out_l1_act1;
            }
            set
            {
                this.Ons_out_l1_act1Changing(value);
                this._s_out_l1_act1 = value;
                this.Ons_out_l1_act1Changed();
                this.OnPropertyChanged("s_out_l1_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _s_out_l1_act1;
        partial void Ons_out_l1_act1Changing(global::System.Nullable<int> value);
        partial void Ons_out_l1_act1Changed();
        /// <summary>
        /// There are no comments for Property s_out_l2_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> s_out_l2_act1
        {
            get
            {
                return this._s_out_l2_act1;
            }
            set
            {
                this.Ons_out_l2_act1Changing(value);
                this._s_out_l2_act1 = value;
                this.Ons_out_l2_act1Changed();
                this.OnPropertyChanged("s_out_l2_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _s_out_l2_act1;
        partial void Ons_out_l2_act1Changing(global::System.Nullable<int> value);
        partial void Ons_out_l2_act1Changed();
        /// <summary>
        /// There are no comments for Property s_out_l3_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> s_out_l3_act1
        {
            get
            {
                return this._s_out_l3_act1;
            }
            set
            {
                this.Ons_out_l3_act1Changing(value);
                this._s_out_l3_act1 = value;
                this.Ons_out_l3_act1Changed();
                this.OnPropertyChanged("s_out_l3_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _s_out_l3_act1;
        partial void Ons_out_l3_act1Changing(global::System.Nullable<int> value);
        partial void Ons_out_l3_act1Changed();
        /// <summary>
        /// There are no comments for Property s_out_all_act1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> s_out_all_act1
        {
            get
            {
                return this._s_out_all_act1;
            }
            set
            {
                this.Ons_out_all_act1Changing(value);
                this._s_out_all_act1 = value;
                this.Ons_out_all_act1Changed();
                this.OnPropertyChanged("s_out_all_act1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _s_out_all_act1;
        partial void Ons_out_all_act1Changing(global::System.Nullable<int> value);
        partial void Ons_out_all_act1Changed();
        /// <summary>
        /// There are no comments for Property cosphi_l1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> cosphi_l1
        {
            get
            {
                return this._cosphi_l1;
            }
            set
            {
                this.Oncosphi_l1Changing(value);
                this._cosphi_l1 = value;
                this.Oncosphi_l1Changed();
                this.OnPropertyChanged("cosphi_l1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _cosphi_l1;
        partial void Oncosphi_l1Changing(global::System.Nullable<int> value);
        partial void Oncosphi_l1Changed();
        /// <summary>
        /// There are no comments for Property cosphi_l2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> cosphi_l2
        {
            get
            {
                return this._cosphi_l2;
            }
            set
            {
                this.Oncosphi_l2Changing(value);
                this._cosphi_l2 = value;
                this.Oncosphi_l2Changed();
                this.OnPropertyChanged("cosphi_l2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _cosphi_l2;
        partial void Oncosphi_l2Changing(global::System.Nullable<int> value);
        partial void Oncosphi_l2Changed();
        /// <summary>
        /// There are no comments for Property cosphi_l3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> cosphi_l3
        {
            get
            {
                return this._cosphi_l3;
            }
            set
            {
                this.Oncosphi_l3Changing(value);
                this._cosphi_l3 = value;
                this.Oncosphi_l3Changed();
                this.OnPropertyChanged("cosphi_l3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _cosphi_l3;
        partial void Oncosphi_l3Changing(global::System.Nullable<int> value);
        partial void Oncosphi_l3Changed();
        /// <summary>
        /// There are no comments for Property thd_l1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> thd_l1
        {
            get
            {
                return this._thd_l1;
            }
            set
            {
                this.Onthd_l1Changing(value);
                this._thd_l1 = value;
                this.Onthd_l1Changed();
                this.OnPropertyChanged("thd_l1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _thd_l1;
        partial void Onthd_l1Changing(global::System.Nullable<int> value);
        partial void Onthd_l1Changed();
        /// <summary>
        /// There are no comments for Property thd_l2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> thd_l2
        {
            get
            {
                return this._thd_l2;
            }
            set
            {
                this.Onthd_l2Changing(value);
                this._thd_l2 = value;
                this.Onthd_l2Changed();
                this.OnPropertyChanged("thd_l2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _thd_l2;
        partial void Onthd_l2Changing(global::System.Nullable<int> value);
        partial void Onthd_l2Changed();
        /// <summary>
        /// There are no comments for Property thd_l3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> thd_l3
        {
            get
            {
                return this._thd_l3;
            }
            set
            {
                this.Onthd_l3Changing(value);
                this._thd_l3 = value;
                this.Onthd_l3Changed();
                this.OnPropertyChanged("thd_l3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _thd_l3;
        partial void Onthd_l3Changing(global::System.Nullable<int> value);
        partial void Onthd_l3Changed();
        /// <summary>
        /// There are no comments for Property v_l1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> v_l1
        {
            get
            {
                return this._v_l1;
            }
            set
            {
                this.Onv_l1Changing(value);
                this._v_l1 = value;
                this.Onv_l1Changed();
                this.OnPropertyChanged("v_l1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _v_l1;
        partial void Onv_l1Changing(global::System.Nullable<int> value);
        partial void Onv_l1Changed();
        /// <summary>
        /// There are no comments for Property v_l2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> v_l2
        {
            get
            {
                return this._v_l2;
            }
            set
            {
                this.Onv_l2Changing(value);
                this._v_l2 = value;
                this.Onv_l2Changed();
                this.OnPropertyChanged("v_l2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _v_l2;
        partial void Onv_l2Changing(global::System.Nullable<int> value);
        partial void Onv_l2Changed();
        /// <summary>
        /// There are no comments for Property v_l3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> v_l3
        {
            get
            {
                return this._v_l3;
            }
            set
            {
                this.Onv_l3Changing(value);
                this._v_l3 = value;
                this.Onv_l3Changed();
                this.OnPropertyChanged("v_l3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _v_l3;
        partial void Onv_l3Changing(global::System.Nullable<int> value);
        partial void Onv_l3Changed();
        /// <summary>
        /// There are no comments for Property p_in_l1_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> p_in_l1_sum
        {
            get
            {
                return this._p_in_l1_sum;
            }
            set
            {
                this.Onp_in_l1_sumChanging(value);
                this._p_in_l1_sum = value;
                this.Onp_in_l1_sumChanged();
                this.OnPropertyChanged("p_in_l1_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _p_in_l1_sum;
        partial void Onp_in_l1_sumChanging(global::System.Nullable<long> value);
        partial void Onp_in_l1_sumChanged();
        /// <summary>
        /// There are no comments for Property p_in_l2_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> p_in_l2_sum
        {
            get
            {
                return this._p_in_l2_sum;
            }
            set
            {
                this.Onp_in_l2_sumChanging(value);
                this._p_in_l2_sum = value;
                this.Onp_in_l2_sumChanged();
                this.OnPropertyChanged("p_in_l2_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _p_in_l2_sum;
        partial void Onp_in_l2_sumChanging(global::System.Nullable<long> value);
        partial void Onp_in_l2_sumChanged();
        /// <summary>
        /// There are no comments for Property p_in_l3_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> p_in_l3_sum
        {
            get
            {
                return this._p_in_l3_sum;
            }
            set
            {
                this.Onp_in_l3_sumChanging(value);
                this._p_in_l3_sum = value;
                this.Onp_in_l3_sumChanged();
                this.OnPropertyChanged("p_in_l3_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _p_in_l3_sum;
        partial void Onp_in_l3_sumChanging(global::System.Nullable<long> value);
        partial void Onp_in_l3_sumChanged();
        /// <summary>
        /// There are no comments for Property p_in_all_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> p_in_all_sum
        {
            get
            {
                return this._p_in_all_sum;
            }
            set
            {
                this.Onp_in_all_sumChanging(value);
                this._p_in_all_sum = value;
                this.Onp_in_all_sumChanged();
                this.OnPropertyChanged("p_in_all_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _p_in_all_sum;
        partial void Onp_in_all_sumChanging(global::System.Nullable<long> value);
        partial void Onp_in_all_sumChanged();
        /// <summary>
        /// There are no comments for Property q_in_l1_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> q_in_l1_sum
        {
            get
            {
                return this._q_in_l1_sum;
            }
            set
            {
                this.Onq_in_l1_sumChanging(value);
                this._q_in_l1_sum = value;
                this.Onq_in_l1_sumChanged();
                this.OnPropertyChanged("q_in_l1_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _q_in_l1_sum;
        partial void Onq_in_l1_sumChanging(global::System.Nullable<long> value);
        partial void Onq_in_l1_sumChanged();
        /// <summary>
        /// There are no comments for Property q_in_l2_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> q_in_l2_sum
        {
            get
            {
                return this._q_in_l2_sum;
            }
            set
            {
                this.Onq_in_l2_sumChanging(value);
                this._q_in_l2_sum = value;
                this.Onq_in_l2_sumChanged();
                this.OnPropertyChanged("q_in_l2_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _q_in_l2_sum;
        partial void Onq_in_l2_sumChanging(global::System.Nullable<long> value);
        partial void Onq_in_l2_sumChanged();
        /// <summary>
        /// There are no comments for Property q_in_l3_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> q_in_l3_sum
        {
            get
            {
                return this._q_in_l3_sum;
            }
            set
            {
                this.Onq_in_l3_sumChanging(value);
                this._q_in_l3_sum = value;
                this.Onq_in_l3_sumChanged();
                this.OnPropertyChanged("q_in_l3_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _q_in_l3_sum;
        partial void Onq_in_l3_sumChanging(global::System.Nullable<long> value);
        partial void Onq_in_l3_sumChanged();
        /// <summary>
        /// There are no comments for Property q_in_all_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> q_in_all_sum
        {
            get
            {
                return this._q_in_all_sum;
            }
            set
            {
                this.Onq_in_all_sumChanging(value);
                this._q_in_all_sum = value;
                this.Onq_in_all_sumChanged();
                this.OnPropertyChanged("q_in_all_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _q_in_all_sum;
        partial void Onq_in_all_sumChanging(global::System.Nullable<long> value);
        partial void Onq_in_all_sumChanged();
        /// <summary>
        /// There are no comments for Property s_in_l1_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> s_in_l1_sum
        {
            get
            {
                return this._s_in_l1_sum;
            }
            set
            {
                this.Ons_in_l1_sumChanging(value);
                this._s_in_l1_sum = value;
                this.Ons_in_l1_sumChanged();
                this.OnPropertyChanged("s_in_l1_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _s_in_l1_sum;
        partial void Ons_in_l1_sumChanging(global::System.Nullable<long> value);
        partial void Ons_in_l1_sumChanged();
        /// <summary>
        /// There are no comments for Property s_in_l2_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> s_in_l2_sum
        {
            get
            {
                return this._s_in_l2_sum;
            }
            set
            {
                this.Ons_in_l2_sumChanging(value);
                this._s_in_l2_sum = value;
                this.Ons_in_l2_sumChanged();
                this.OnPropertyChanged("s_in_l2_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _s_in_l2_sum;
        partial void Ons_in_l2_sumChanging(global::System.Nullable<long> value);
        partial void Ons_in_l2_sumChanged();
        /// <summary>
        /// There are no comments for Property s_in_l3_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> s_in_l3_sum
        {
            get
            {
                return this._s_in_l3_sum;
            }
            set
            {
                this.Ons_in_l3_sumChanging(value);
                this._s_in_l3_sum = value;
                this.Ons_in_l3_sumChanged();
                this.OnPropertyChanged("s_in_l3_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _s_in_l3_sum;
        partial void Ons_in_l3_sumChanging(global::System.Nullable<long> value);
        partial void Ons_in_l3_sumChanged();
        /// <summary>
        /// There are no comments for Property s_in_all_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> s_in_all_sum
        {
            get
            {
                return this._s_in_all_sum;
            }
            set
            {
                this.Ons_in_all_sumChanging(value);
                this._s_in_all_sum = value;
                this.Ons_in_all_sumChanged();
                this.OnPropertyChanged("s_in_all_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _s_in_all_sum;
        partial void Ons_in_all_sumChanging(global::System.Nullable<long> value);
        partial void Ons_in_all_sumChanged();
        /// <summary>
        /// There are no comments for Property p_out_l1_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> p_out_l1_sum
        {
            get
            {
                return this._p_out_l1_sum;
            }
            set
            {
                this.Onp_out_l1_sumChanging(value);
                this._p_out_l1_sum = value;
                this.Onp_out_l1_sumChanged();
                this.OnPropertyChanged("p_out_l1_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _p_out_l1_sum;
        partial void Onp_out_l1_sumChanging(global::System.Nullable<long> value);
        partial void Onp_out_l1_sumChanged();
        /// <summary>
        /// There are no comments for Property p_out_l2_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> p_out_l2_sum
        {
            get
            {
                return this._p_out_l2_sum;
            }
            set
            {
                this.Onp_out_l2_sumChanging(value);
                this._p_out_l2_sum = value;
                this.Onp_out_l2_sumChanged();
                this.OnPropertyChanged("p_out_l2_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _p_out_l2_sum;
        partial void Onp_out_l2_sumChanging(global::System.Nullable<long> value);
        partial void Onp_out_l2_sumChanged();
        /// <summary>
        /// There are no comments for Property p_out_l3_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> p_out_l3_sum
        {
            get
            {
                return this._p_out_l3_sum;
            }
            set
            {
                this.Onp_out_l3_sumChanging(value);
                this._p_out_l3_sum = value;
                this.Onp_out_l3_sumChanged();
                this.OnPropertyChanged("p_out_l3_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _p_out_l3_sum;
        partial void Onp_out_l3_sumChanging(global::System.Nullable<long> value);
        partial void Onp_out_l3_sumChanged();
        /// <summary>
        /// There are no comments for Property p_out_all_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> p_out_all_sum
        {
            get
            {
                return this._p_out_all_sum;
            }
            set
            {
                this.Onp_out_all_sumChanging(value);
                this._p_out_all_sum = value;
                this.Onp_out_all_sumChanged();
                this.OnPropertyChanged("p_out_all_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _p_out_all_sum;
        partial void Onp_out_all_sumChanging(global::System.Nullable<long> value);
        partial void Onp_out_all_sumChanged();
        /// <summary>
        /// There are no comments for Property q_out_l1_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> q_out_l1_sum
        {
            get
            {
                return this._q_out_l1_sum;
            }
            set
            {
                this.Onq_out_l1_sumChanging(value);
                this._q_out_l1_sum = value;
                this.Onq_out_l1_sumChanged();
                this.OnPropertyChanged("q_out_l1_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _q_out_l1_sum;
        partial void Onq_out_l1_sumChanging(global::System.Nullable<long> value);
        partial void Onq_out_l1_sumChanged();
        /// <summary>
        /// There are no comments for Property q_out_l2_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> q_out_l2_sum
        {
            get
            {
                return this._q_out_l2_sum;
            }
            set
            {
                this.Onq_out_l2_sumChanging(value);
                this._q_out_l2_sum = value;
                this.Onq_out_l2_sumChanged();
                this.OnPropertyChanged("q_out_l2_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _q_out_l2_sum;
        partial void Onq_out_l2_sumChanging(global::System.Nullable<long> value);
        partial void Onq_out_l2_sumChanged();
        /// <summary>
        /// There are no comments for Property q_out_l3_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> q_out_l3_sum
        {
            get
            {
                return this._q_out_l3_sum;
            }
            set
            {
                this.Onq_out_l3_sumChanging(value);
                this._q_out_l3_sum = value;
                this.Onq_out_l3_sumChanged();
                this.OnPropertyChanged("q_out_l3_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _q_out_l3_sum;
        partial void Onq_out_l3_sumChanging(global::System.Nullable<long> value);
        partial void Onq_out_l3_sumChanged();
        /// <summary>
        /// There are no comments for Property q_out_all_sum in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> q_out_all_sum
        {
            get
            {
                return this._q_out_all_sum;
            }
            set
            {
                this.Onq_out_all_sumChanging(value);
                this._q_out_all_sum = value;
                this.Onq_out_all_sumChanged();
                this.OnPropertyChanged("q_out_all_sum");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _q_out_all_sum;
        partial void Onq_out_all_sumChanging(global::System.Nullable<long> value);
        partial void Onq_out_all_sumChanged();
        /// <summary>
        /// There are no comments for smadevice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public smadevice smadevice
        {
            get
            {
                return this._smadevice;
            }
            set
            {
                this._smadevice = value;
                this.OnPropertyChanged("smadevice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private smadevice _smadevice;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for smardModel.smadevice in the schema.
    /// </summary>
    /// <KeyProperties>
    /// deviceID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("smadevice")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("deviceID")]
    public partial class smadevice : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new smadevice object.
        /// </summary>
        /// <param name="deviceID">Initial value of deviceID.</param>
        /// <param name="devicetype">Initial value of devicetype.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static smadevice Createsmadevice(int deviceID, int devicetype)
        {
            smadevice smadevice = new smadevice();
            smadevice.deviceID = deviceID;
            smadevice.devicetype = devicetype;
            return smadevice;
        }
        /// <summary>
        /// There are no comments for Property deviceID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int deviceID
        {
            get
            {
                return this._deviceID;
            }
            set
            {
                this.OndeviceIDChanging(value);
                this._deviceID = value;
                this.OndeviceIDChanged();
                this.OnPropertyChanged("deviceID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _deviceID;
        partial void OndeviceIDChanging(int value);
        partial void OndeviceIDChanged();
        /// <summary>
        /// There are no comments for Property devicetype in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int devicetype
        {
            get
            {
                return this._devicetype;
            }
            set
            {
                this.OndevicetypeChanging(value);
                this._devicetype = value;
                this.OndevicetypeChanged();
                this.OnPropertyChanged("devicetype");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _devicetype;
        partial void OndevicetypeChanging(int value);
        partial void OndevicetypeChanged();
        /// <summary>
        /// There are no comments for Property serialnumber in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> serialnumber
        {
            get
            {
                return this._serialnumber;
            }
            set
            {
                this.OnserialnumberChanging(value);
                this._serialnumber = value;
                this.OnserialnumberChanged();
                this.OnPropertyChanged("serialnumber");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _serialnumber;
        partial void OnserialnumberChanging(global::System.Nullable<decimal> value);
        partial void OnserialnumberChanged();
        /// <summary>
        /// There are no comments for Property hostname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string hostname
        {
            get
            {
                return this._hostname;
            }
            set
            {
                this.OnhostnameChanging(value);
                this._hostname = value;
                this.OnhostnameChanged();
                this.OnPropertyChanged("hostname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _hostname;
        partial void OnhostnameChanging(string value);
        partial void OnhostnameChanged();
        /// <summary>
        /// There are no comments for Property ipaddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ipaddress
        {
            get
            {
                return this._ipaddress;
            }
            set
            {
                this.OnipaddressChanging(value);
                this._ipaddress = value;
                this.OnipaddressChanged();
                this.OnPropertyChanged("ipaddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ipaddress;
        partial void OnipaddressChanging(string value);
        partial void OnipaddressChanged();
        /// <summary>
        /// There are no comments for Property targetaddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string targetaddress
        {
            get
            {
                return this._targetaddress;
            }
            set
            {
                this.OntargetaddressChanging(value);
                this._targetaddress = value;
                this.OntargetaddressChanged();
                this.OnPropertyChanged("targetaddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _targetaddress;
        partial void OntargetaddressChanging(string value);
        partial void OntargetaddressChanged();
        /// <summary>
        /// There are no comments for Property firmware in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string firmware
        {
            get
            {
                return this._firmware;
            }
            set
            {
                this.OnfirmwareChanging(value);
                this._firmware = value;
                this.OnfirmwareChanged();
                this.OnPropertyChanged("firmware");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _firmware;
        partial void OnfirmwareChanging(string value);
        partial void OnfirmwareChanged();
        /// <summary>
        /// There are no comments for log_energymeter in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<log_energymeter> log_energymeter
        {
            get
            {
                return this._log_energymeter;
            }
            set
            {
                this._log_energymeter = value;
                this.OnPropertyChanged("log_energymeter");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<log_energymeter> _log_energymeter = new global::System.Data.Services.Client.DataServiceCollection<log_energymeter>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// There are no comments for smadevicetype in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public smadevicetype smadevicetype
        {
            get
            {
                return this._smadevicetype;
            }
            set
            {
                this._smadevicetype = value;
                this.OnPropertyChanged("smadevicetype");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private smadevicetype _smadevicetype;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for smardModel.smadevicetype in the schema.
    /// </summary>
    /// <KeyProperties>
    /// devicetypeID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("smadevicetype")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("devicetypeID")]
    public partial class smadevicetype : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new smadevicetype object.
        /// </summary>
        /// <param name="devicetypeID">Initial value of devicetypeID.</param>
        /// <param name="devicetypeName">Initial value of devicetypeName.</param>
        /// <param name="devicetypeClass">Initial value of devicetypeClass.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static smadevicetype Createsmadevicetype(int devicetypeID, string devicetypeName, string devicetypeClass)
        {
            smadevicetype smadevicetype = new smadevicetype();
            smadevicetype.devicetypeID = devicetypeID;
            smadevicetype.devicetypeName = devicetypeName;
            smadevicetype.devicetypeClass = devicetypeClass;
            return smadevicetype;
        }
        /// <summary>
        /// There are no comments for Property devicetypeID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int devicetypeID
        {
            get
            {
                return this._devicetypeID;
            }
            set
            {
                this.OndevicetypeIDChanging(value);
                this._devicetypeID = value;
                this.OndevicetypeIDChanged();
                this.OnPropertyChanged("devicetypeID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _devicetypeID;
        partial void OndevicetypeIDChanging(int value);
        partial void OndevicetypeIDChanged();
        /// <summary>
        /// There are no comments for Property devicetypeName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string devicetypeName
        {
            get
            {
                return this._devicetypeName;
            }
            set
            {
                this.OndevicetypeNameChanging(value);
                this._devicetypeName = value;
                this.OndevicetypeNameChanged();
                this.OnPropertyChanged("devicetypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _devicetypeName;
        partial void OndevicetypeNameChanging(string value);
        partial void OndevicetypeNameChanged();
        /// <summary>
        /// There are no comments for Property devicetypeClass in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string devicetypeClass
        {
            get
            {
                return this._devicetypeClass;
            }
            set
            {
                this.OndevicetypeClassChanging(value);
                this._devicetypeClass = value;
                this.OndevicetypeClassChanged();
                this.OnPropertyChanged("devicetypeClass");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _devicetypeClass;
        partial void OndevicetypeClassChanging(string value);
        partial void OndevicetypeClassChanged();
        /// <summary>
        /// There are no comments for smadevice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<smadevice> smadevice
        {
            get
            {
                return this._smadevice;
            }
            set
            {
                this._smadevice = value;
                this.OnPropertyChanged("smadevice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<smadevice> _smadevice = new global::System.Data.Services.Client.DataServiceCollection<smadevice>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
